name: Generate Fish Animation
on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/only-svg/github-contribution-grid-fish.svg?color_snake=#9966FF&snake=ğŸŸ&color_dots=#D8BFD8,#BA55D3,#9932CC,#800080,#4B0082&color_empty=#000000
            dist/only-svg/github-contribution-grid-fish-dark.svg?palette=github-dark&snake=ğŸ &color_snake=#9966FF&color_empty=#000000
            dist/only-svg/github-contribution-grid-fish-purple.svg?color_snake=#9966FF&snake=ğŸŸ&color_dots=#D8BFD8,#BA55D3,#9932CC,#800080,#4B0082&color_empty=#000000

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/docker/github-contribution-grid-fish.svg?color_snake=#9966FF&snake=ğŸŸ&color_dots=#D8BFD8,#BA55D3,#9932CC,#800080,#4B0082&color_empty=#000000
            dist/docker/github-contribution-grid-fish-dark.svg?palette=github-dark&snake=ğŸ &color_snake=#9966FF&color_empty=#000000
            dist/docker/github-contribution-grid-fish.gif?color_snake=#9966FF&snake=ğŸŸ&color_dots=#D8BFD8,#BA55D3,#9932CC,#800080,#4B0082&color_empty=#000000

      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/only-svg/github-contribution-grid-fish.svg
          test -f dist/only-svg/github-contribution-grid-fish-dark.svg
          test -f dist/only-svg/github-contribution-grid-fish-purple.svg
          test -f dist/docker/github-contribution-grid-fish.svg
          test -f dist/docker/github-contribution-grid-fish-dark.svg
          test -f dist/docker/github-contribution-grid-fish.gif

      - name: push fish animations to the output branch
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: manual-run-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
